// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Study_Buddys_Backend.Context;

#nullable disable

namespace Study_Buddys_Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250402184427_UpdateCommunityModel")]
    partial class UpdateCommunityModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Study_Buddys_Backend.Models.CommunityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommunityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunityDifficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CommunityIsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("CommunityIsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("CommunityMemberCount")
                        .HasColumnType("int");

                    b.Property<string>("CommunityMembers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommunityOwnerID")
                        .HasColumnType("int");

                    b.Property<string>("CommunityOwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunityRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunitySubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCommunityOwner")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Communitys");
                });

            modelBuilder.Entity("Study_Buddys_Backend.Models.UserModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommunityRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JoinedCommunitys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnedCommunitys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
